[package]
name = "mpart-async"
version = "0.1.0"
authors = ["cetra3 <cetra3@hotmail.com>"]
license = "MIT/Apache-2.0"
description = "Asynchronous (Futures-Base) Multipart Requests for Rust"
repository = "https://github.com/cetra3/mpart-async"
readme = "README.md"

[dependencies]
bytes = "0.4.6"
futures = "0.1.21"
failure = "0.1.1"
rand = "0.4"
log = "0.4.1"
